name: run-tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: zip
          coverage: none
      - name: Install composer dependencies
        uses: ramsey/composer-install@v1
      - name: Execute tests
        env:
          WWDR_CONTENT: ${{ secrets.WWDR_CONTENT }}
          CERTIFICATE_CONTENT: ${{ secrets.CERTIFICATE_CONTENT }}
          PASSES_APPLE_PASSWORD: ${{ secrets.PASSES_APPLE_PASSWORD }}
        run: |
          cp .env.example .env
          mkdir tests/certs
          echo $CERTIFICATE_CONTENT | base64 --decode > tests/certs/certificate.p12
          echo $WWDR_CONTENT | base64 --decode > tests/certs/wwdr.pem
          vendor/bin/phpunit
